### ISSUE TITLE
Unable to dynamically load USD in Maya 2023

### ISSUE THREAD

**Issue by IRONIC3D** [serguei-k/maya-math-nodes#21]
When trying to build for 2023 on Windows everything works fine until the time to load the plugin in 2023 it produces the following error:

`// Error: file: C:/Program Files/Autodesk/Maya2023/scripts/others/pluginWin.mel line 316: Unable to dynamically load : C:/src/maya-math-nodes/dist/MayaMathNodes/plug-ins/2023/mayaMathNodes.mll
// The specified procedure could not be found.
// Error: file: C:/Program Files/Autodesk/Maya2023/scripts/others/pluginWin.mel line 316: The specified procedure could not be found.
//  (mayaMathNodes)`

Project configured for 2023.

**Comment by IRONIC3D** [comment]
Changed the paths to Maya 2023 in VS project for both the compiler and linker and now the plugin functions properly in 2023.

**Comment by serguei-k** [comment]
Thanks for the reminder, I defaulted the build to 2023!
