### ISSUE TITLE
Modulo node suggestion

### ISSUE THREAD

**Issue by darkvertex** [serguei-k/maya-math-nodes#8]
Hi Serguei!

I noticed there's no Modulo node.

It could be very useful for looping values and actually it's not even available in Maya by default. You'd think the Expression Editor's many basic math functions would have a `mod()` in there but it doesn't, nor is there `fmod()` (which exists in MEL, boo!)

I'm not very good at C++ yet or I'd try to contribute such a node myself, but just wanted to put in the feature suggestion if you find the time.

Cheers! Great work!

**Comment by serguei-k** [comment]
Hi Alan,

There is support for mod, it is called ModulusInt in the node set.
I currently don't support fmod though, but open to adding it.

**Comment by darkvertex** [comment]
Ah, it was hiding in the `Divide.h` source! Sorry I missed that.

**Comment by serguei-k** [comment]
No worries, best thing is to look at Plugin.cpp to see all the defined node variants.
